# Generated by Django 3.0.5 on 2020-05-25 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('pesel', models.BigIntegerField(default=11223344555, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)], verbose_name='PESEL')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('nr', models.PositiveSmallIntegerField(blank=True, verbose_name='Number')),
                ('zip_code', models.CharField(blank=True, max_length=6, verbose_name='Zip Code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('birthday', models.DateField(blank=True)),
                ('nr_in_main_book', models.PositiveSmallIntegerField(blank=True, verbose_name='Number in The Main Book')),
                ('nr_in_ward_book', models.PositiveSmallIntegerField(blank=True, verbose_name='Number in The Ward Book')),
                ('agreed_to_tests', models.BooleanField(default=False, verbose_name='Agreed to the tests')),
            ],
        ),
    ]
