# Generated by Django 3.0.5 on 2020-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nr',
            field=models.PositiveSmallIntegerField(verbose_name='Numer'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nr_in_main_book',
            field=models.CharField(max_length=100, verbose_name='Numer w Książce Głównej'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nr_in_ward_book',
            field=models.CharField(max_length=100, verbose_name='Numer w Książce Oddziałowej'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(max_length=6, verbose_name='Kod pocztowy'),
        ),
    ]
