# Generated by Django 3.0.5 on 2020-06-07 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='agreed_to_tests',
            field=models.BooleanField(default=False, verbose_name='Zgoda na wykonanie badań'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nr',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Numer'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nr_in_main_book',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Numer w Książce Głównej'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nr_in_ward_book',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Numer w Książce Oddziałowej'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pesel',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)], verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Kod pocztowy'),
        ),
    ]
