# Generated by Django 3.0.5 on 2020-06-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200607_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nr_in_main_book',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numer w Książce Głównej'),
        ),
    ]
