# Generated by Django 3.0.5 on 2020-06-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20200607_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nr_in_ward_book',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numer w Książce Oddziałowej'),
        ),
    ]
