# Generated by Django 3.0.5 on 2020-05-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('day_shift', models.BooleanField(default=False)),
                ('night_shift', models.BooleanField(default=False)),
                ('additional', models.BooleanField(default=False)),
                ('diet', models.CharField(choices=[('LI', 'Płynna'), ('YE', 'Tak'), ('NO', 'Nie')], default='NO', max_length=2, verbose_name='Dieta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaecesExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('day_shift', models.BooleanField(default=False)),
                ('night_shift', models.BooleanField(default=False)),
                ('additional', models.BooleanField(default=False)),
                ('faeces', models.PositiveSmallIntegerField(verbose_name='Stolec')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PressureExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('day_shift', models.BooleanField(default=False)),
                ('night_shift', models.BooleanField(default=False)),
                ('additional', models.BooleanField(default=False)),
                ('systole', models.PositiveSmallIntegerField(verbose_name='Ciśnienie Skurczowe')),
                ('diastole', models.PositiveSmallIntegerField(verbose_name='Ciśnienie Rozkurczowe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PulseExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('day_shift', models.BooleanField(default=False)),
                ('night_shift', models.BooleanField(default=False)),
                ('additional', models.BooleanField(default=False)),
                ('pulse', models.PositiveSmallIntegerField(verbose_name='Tętno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperatureExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('day_shift', models.BooleanField(default=False)),
                ('night_shift', models.BooleanField(default=False)),
                ('additional', models.BooleanField(default=False)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperatura')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
