# Generated by Django 3.0.5 on 2020-06-18 18:45

from django.db import migrations, models
import examinations.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('made_on', models.DateTimeField()),
                ('day_shift', models.BooleanField(default=False)),
                ('night_shift', models.BooleanField(default=False)),
                ('additional', models.BooleanField(default=False)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3, validators=[examinations.validators.validate_temperature_range], verbose_name='Temperatura')),
                ('pulse', models.PositiveSmallIntegerField(validators=[examinations.validators.validate_pulse_range], verbose_name='Tętno')),
                ('systole', models.PositiveSmallIntegerField(validators=[examinations.validators.validate_systole_range], verbose_name='Ciśnienie Skurczowe')),
                ('diastole', models.PositiveSmallIntegerField(validators=[examinations.validators.validate_diastole_range], verbose_name='Ciśnienie Rozkurczowe')),
                ('diet', models.CharField(choices=[('LI', 'Płynna'), ('YE', 'Tak'), ('NO', 'Nie')], default='NO', max_length=2, verbose_name='Dieta')),
                ('faeces', models.PositiveSmallIntegerField(verbose_name='Stolec')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
