# Generated by Django 3.0.5 on 2020-05-25 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_auto_20200525_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaecesExamination',
            fields=[
                ('examination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='examinations.Examination')),
                ('faeces', models.PositiveSmallIntegerField(verbose_name='Stolec')),
            ],
            options={
                'abstract': False,
            },
            bases=('examinations.examination',),
        ),
    ]
