# Generated by Django 3.0.5 on 2020-06-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_auto_20200528_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrecommendation',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='faecesexamination',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pressureexamination',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pulseexamination',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temperatureexamination',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
