# Generated by Django 3.0.5 on 2020-06-28 19:52

from django.db import migrations, models
import examinations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0003_auto_20200628_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[examinations.validators.validate_temperature_range], verbose_name='Temperatura'),
        ),
    ]
