# Generated by Django 3.0.5 on 2020-05-25 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0003_faecesexamination'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressureExamination',
            fields=[
                ('examination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='examinations.Examination')),
                ('systole', models.PositiveSmallIntegerField(verbose_name='Ciśnienie Skurczowe')),
                ('diastole', models.PositiveSmallIntegerField(verbose_name='Ciśnienie Rozkurczowe')),
            ],
            options={
                'abstract': False,
            },
            bases=('examinations.examination',),
        ),
    ]
