# Generated by Django 3.0.5 on 2020-06-11 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0003_auto_20200611_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrecommendation',
            name='really_created',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faecesexamination',
            name='really_created',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressureexamination',
            name='really_created',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulseexamination',
            name='really_created',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatureexamination',
            name='really_created',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietrecommendation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faecesexamination',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pressureexamination',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pulseexamination',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='temperatureexamination',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
