# Generated by Django 3.0.5 on 2020-05-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_pressureexamination'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('examination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='examinations.Examination')),
                ('diet', models.CharField(choices=[('LI', 'Płynna'), ('YE', 'Tak'), ('NO', 'Nie')], default='NO', max_length=2, verbose_name='Dieta')),
            ],
            options={
                'abstract': False,
            },
            bases=('examinations.examination',),
        ),
    ]
