# Generated by Django 3.0.5 on 2020-06-14 18:00

from django.db import migrations, models
import examinations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_auto_20200611_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureexamination',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[examinations.validators.validate_temperature_range], verbose_name='Temperatura'),
        ),
    ]
