# Generated by Django 3.0.5 on 2020-06-14 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0005_auto_20200614_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureexamination',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(35)], verbose_name='Temperatura'),
        ),
    ]
