# Generated by Django 3.0.5 on 2020-06-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0005_auto_20200628_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='diet',
            field=models.CharField(choices=[('', '-- Wybierz opcję --'), ('LI', 'Płynna'), ('YE', 'Tak'), ('NO', 'Nie')], default='', max_length=2, verbose_name='Dieta'),
        ),
    ]
