# Generated by Django 3.0.5 on 2020-05-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor',
            field=models.BooleanField(default=False, verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='user',
            name='nurse',
            field=models.BooleanField(default=True, verbose_name='Nurse'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupational_therapist',
            field=models.BooleanField(default=False, verbose_name='Occupational therapist'),
        ),
        migrations.AddField(
            model_name='user',
            name='pesel',
            field=models.PositiveIntegerField(default=77071707177, verbose_name='PESEL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='physiotherapist',
            field=models.BooleanField(default=False, verbose_name='Physiotherapist'),
        ),
        migrations.AddField(
            model_name='user',
            name='psychologist',
            field=models.BooleanField(default=False, verbose_name='Psychologist'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='77071777177', max_length=255, verbose_name='Surname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
